# Generated by Django 6.0.1 on 2026-02-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_deliverypincode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypincode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
