# Generated by Django 6.0.1 on 2026-03-09 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_parameter_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', help_text='Product category from parameter_master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bouquets', to='masters.parameter_master'),
        ),
    ]
