# Generated by Django 6.0.1 on 2026-03-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_bouquet_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='buy_now',
            field=models.IntegerField(default=0, help_text='0: WhatsApp Inquiry, 1: Normal Buy Now'),
        ),
    ]
