# Generated by Django 4.2.23 on 2026-09-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_contactinquiry_recentlyviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='delivery_info',
            field=models.CharField(blank=True, max_length=1555, null=True),
        ),
    ]
