# Generated by Django 4.2.23 on 2026-09-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'email_otp',
                'indexes': [models.Index(fields=['email'], name='email_otp_email_a21bd7_idx'), models.Index(fields=['otp_code'], name='email_otp_otp_cod_04b0f2_idx'), models.Index(fields=['created_at'], name='email_otp_created_f42155_idx')],
            },
        ),
    ]
